import Head from 'next/head';
import Header from './Header';
import Footer from './Footer';
const Layout = ({ children, title, showHead=true, showFooter=true }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />        
      </Head>
      <div>
      {showHead==true && <Header />}
        <main>{children}</main>
      {showFooter==true && <Footer />}
      </div>
    </>
  );
};

export default Layout;
